FROM python:2.7

MAINTAINER Chris Henry <henry.christopher@gmail.com>

ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
  apt-get install -yq --no-install-recommends \
  mysql-client \
  ca-certificates \
  locales \
  vim && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen

# Upgrade pip
RUN mkdir -p /opt/app/code/
WORKDIR /opt/app/code/

RUN pip install --upgrade pip

COPY requirements.txt /root/requirements.txt
RUN pip --no-cache-dir install -r /root/requirements.txt
